apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pgsql
  namespace: insurance-app
spec:
  serviceName: pgsql
  replicas: 1
  selector:
    matchLabels:
      app: pgsql
  template:
    metadata:
      labels:
        app: pgsql
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
              name: postgres
          envFrom:
            - secretRef:
                name: pgsql-secret
            - configMapRef:
                name: pgsql-config
          volumeMounts:
            - name: pgsql-storage
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "admin"]
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "admin"]
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: pgsql-storage
          persistentVolumeClaim:
            claimName: pgsql-pvc
