# Persistent Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgsql-pv
  namespace: insurance-app
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:   # kind supports hostPath volumes on local nodes
    path: /data/pgsql
  persistentVolumeReclaimPolicy: Retain

---
# Persistent Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgsql-pvc
  namespace: insurance-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
